development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: soccer
  pool: 5
  username: root
  password: P@ssw0rd

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: soccer
  pool: 5
  username: root
  password: P@ssw0rd

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: soccer
  pool: 5
  username: root
  password: P@ssw0rd